version: '3'
services:
  builder:
    build: "wildfly"
    working_dir: "/project"
    user: "root"
    volumes:
      # current project
      - "./:/project"
      # maven repository cache
      - "builder-maven-cache:/root/.m2/"
  client:
    build: "wildfly"
    command: "/opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0"
    ports:
      - "8080:8080" # TCP
      - "9990:9990" # admin console (user: "admin", password: "Admin#70365")
    networks:
      w2w-network:
        aliases:
          - w2w-client
    volumes:
      - "./deployments-client:/opt/jboss/wildfly/standalone/deployments/"
  server:
    build: "wildfly"
    ports:
      - "8081:8080" # TCP
      - "9991:9990" # admin console
    networks:
      w2w-network:
        aliases:
          - w2w-server
    volumes:
      - "./deployments-server:/opt/jboss/wildfly/standalone/deployments/"

networks:
  w2w-network:
volumes:
  builder-maven-cache:
